---
include:
  - { project: lianatech/devops/cicd-templates, file: secret-detection.gitlab-ci.yml, ref: v1.22.9 }

secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "false"

stages:
  - test
